### ISSUE TITLE
Inheriting Engineer PDA causes error

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFCustomWeaponsX#16]
CWX states that the PDA shows a "non-existent" slot if it is set in the "inherits" field. In order for it to work, it must be overwritten with "used_by_classes" and set onto "Utility".

**Comment by nosoop** [comment]
To save time in the future, mind posting the item config entry, or at least the name of the item?  It sounds like you meant the error that reports items in "non-visible" slots.

Looks like some bits need to be changed in the loadout slot visibility handling, should be fixed shortly.

**Comment by SoulBlast35** [comment]
Works great. Almost got tripped up with "TF_WEAPON_BUILDER" before realising thats NOT the PDA, its the Toolbox the engy carries after selecting a building with the PDA.
