### ISSUE TITLE
Set DamageType Ignite not working

### ISSUE THREAD

**Issue by Sharkmaw** [nosoop/SM-TFCustomWeaponsX#17]
not sure this is exact right github page for this issue but yeah the attribute doesn't work

**Comment by nosoop** [comment]
Known issue with the game, but is unrelated to this project &mdash; CWX is only responsible for applying attributes to items, whether or not those attributes work is a different matter.

My [Attribute Extended Support Fixes](https://github.com/nosoop/SM-TFAttributeSupport) project does patch the game so `Set DamageType Ignite` works on all weapons; see nosoop/SM-TFAttributeSupport#1 for more information.

**Comment by nosoop** [comment]
That said, it's probably a good idea to link that project in the README.  I'll go ahead and add that in; thank you for the report.
