### ISSUE TITLE
Fix non-medieval weapons being useable in medieval mode

### ISSUE THREAD

**Issue by jack5github** [nosoop/SM-TFCustomWeaponsX#26]
It appears that every single weapon a server operator creates, regardless of its attributes, is always equippable when medieval mode is active. This makes it impossible to play regular medieval mode, for there will be players that equip these custom weapons during such maps or when the medieval ConVar is turned on.

**Comment by nosoop** [comment]
Latest commit should make this work.  Do note that if `keep_static_attrs` has been disabled within the item config, you will need to add `allowed in medieval mode` to the `attributes_game` section.
