### ISSUE TITLE
A bunch of gamebreaking issues found. (Engineer Buildings Disappearing, Stickies Disappearing, etc.)

### ISSUE THREAD

**Issue by SnowySnowtime** [nosoop/SM-TFCustomWeaponsX#28]
Currently, I'm compiling a list of issues I had found whilst using this plugin on my server. There's a few small ones, but on the other hand, a decent chunk that is game-breaking that is REALLY annoying the players. Here's a list of the few I found, along with replication:
These all occur at random.

``Engineer Buildings Disappearing, and Stickies Disappearing.``
Replication: Build or deploy a sticky, and switch to a CWX weapon from stock. May even occur if you just switch weapons outright. This is a major annoyance to Engineer and Demo's, for obvious reasons.

``Players may lose one, multiple; or all weaponry, upon spawning.``
Replication: Spawn. I'm not sure why this one happens. This seems to be an odd case where some people will experience this, and be incapable of playing outright, while others will be able to play without issues whatsoever. This one occurs even if the player doesn't use CWX weapons whatsoever. I've had cases where players would lose their primary weapon only, but never lose their other weapons. but then some who'd always lose their weapons, and even some who would lose just their melee. It's weird and inconsistent. Since this issue never occurs to me, it may be related to when a player joins.

``Wearables double their attributes on touching a resupply locker on classes that do not originally have them``
Replication: Self Explanatory. Touch resupply with a wearable on a class that doesn't usually have it, and it'll double it's attributes. Best seen with health increases and health regen.
I'm certain there's more, but I'll need to record these issues occurring. Due to the fact that only the first and third one affects me, I'm going to have to wait for players to join to record the weapon misplacement issue.

I've been watching the console but I don't see anything that could correlate to the weapons disappearing. It just happens. I tried it with no other plugins enabled besides the CWX framework, base Sourcemod, and its Attribute framework and it still occurs for players. Further investigation required.

**Comment by SnowySnowtime** [comment]
If any additional information is required, let me know. I'll provide with what i can.

**Comment by nosoop** [comment]
Hello; thanks for reporting.

> Stickies Disappearing
I'm able to reproduce this if a new weapon is selected while in a valid spawn room.
That seems like the intended current behavior when players update weapons in spawn.  That said, the game's own loadout switching and respawn mechanic doesn't trigger this, so I'll split it out into a separate issue so it can be closed out separately.

> Engineer Buildings Disappearing
I'm unable to reproduce this with the method described above.  Which would make sense, since buildings aren't destroyed on death / spawn.

> Players may lose one, multiple; or all weaponry, upon spawning.
Also unable to reproduce this.  One idea I can think of is that this may be related to connectivity issues with the game coordinator, but otherwise I can't think of any reason why weapons would not be granted.

> Wearables
Yeah, I think I can see where this issue could come from.  Will split it out as well.

**Comment by SnowySnowtime** [comment]
The one with engineer's buildings is seemingly random sadly. I do have a recording of it occurring, and it sometimes happens in play. It was big enough to report. Give me a few moments to upload.

**Comment by SnowySnowtime** [comment]
> Players may lose one, multiple; or all weaponry, upon spawning.
This one may be related to the time a player joins. If they're the first one, etc. This issue never occurs to me, but _almost_ always occurs to others. This is just correlation however, and may not be the cause.

**Comment by SnowySnowtime** [comment]
An example of engineer buildings randomly disappearing. This may occur even in non-mvm based servers.
https://user-images.githubusercontent.com/47854261/129664189-d5a4183d-24a2-4364-b6ab-3cdcea1e7dc2.mp4

**Comment by nosoop** [comment]
I'll look into it when I have the time, but I can't think of anything specifically within CWX that would trigger Engineer buildings disappearing (especially individual ones).  I guess I'll create an exhaustive build for you that logs all function calls within a few hours, if not the next day.

**Comment by SnowySnowtime** [comment]
Alright.

**Comment by SnowySnowtime** [comment]
Updated to the new release, Demo's stickies still disappears. This behavior is only shown when using CWX.

https://user-images.githubusercontent.com/47854261/129791962-ac258d36-0568-48e6-b016-fc275f9f1330.mp4

**Comment by nosoop** [comment]
Can you provide a full list of plugins and extensions currently active on the server (including versions)? Also, what operating system is the server running on?
I can't think of anything within the CWX core plugin that would cause this behavior directly, so I'd guess it's either a faulty attribute or an overzealous entity limiter.

**Comment by nosoop** [comment]
If you have a minimal setup that you can replicate this on, you can also create an archive of all the addons and send that to me in some form.  Would probably be easier for me to look over.

**Comment by nosoop** [comment]
Attached is an exhaustive logging build, which adds messages for most things within `cwx.sp` (the main code file).

[package.zip](https://github.com/nosoop/SM-TFCustomWeaponsX/files/7005034/package.zip)

**Comment by SnowySnowtime** [comment]
Operating System for all servers is Windows 10.
The two servers run somewhat different plugins, I'll compile them into two separate text files.
[server_1.txt](https://github.com/nosoop/SM-TFCustomWeaponsX/files/7005292/server_1.txt)

These issues persist on the other server as well.
[server_2.txt](https://github.com/nosoop/SM-TFCustomWeaponsX/files/7005293/server_2.txt)
I'm starting to believe that it could be a TF2Items conflict due to how the two plugins work, but that's more-so out of experience with GMod addons, not sure if that thinking applies to sourcepawn.

I'll go isolate the CWX plugin itself, and work my way up using your verbose logging build.

**Comment by nosoop** [comment]
Ah, TF2Items.  You might be seeing something related to [this issue I posted a few years ago](https://forums.alliedmods.net/showthread.php?t=315096) with the disappearing weapons.

DHooks historically had Windows-specific quirks so that might also be an issue, but DHooks in general is really finicky with what return types a developer should be using.

The verbose build might have formatting log issues, so I'll take a look into that.

**Comment by nosoop** [comment]
Ah, yeah. Screwed up on the formatting on that message.  Fixed package and source attached.

[package.zip](https://github.com/nosoop/SM-TFCustomWeaponsX/files/7005642/package.zip)

**Comment by SnowySnowtime** [comment]
Alright, downloading.

**Comment by SnowySnowtime** [comment]
I really do hope that TF2Items isn't the cause. It's much better than TF2Attributes is in most instances, IMO. I'll go test to see if TF2items is the cause of this bug once I do a double check on the updated verbose build.

**Comment by nosoop** [comment]
It could be something within the starter pack attribute collection as well.  Unfortunately, between the additional maintenance complexity and DHooks in general, Windows is a second-class platform.

**Comment by nosoop** [comment]
Regarding the attribute doubling, please provide a sample config on issue #30 so I can validate.  I tested the fix with a copy of a Chargin' Targe with bonus maxhealth on an Engineer and that seemed to work fine.

**Comment by SnowySnowtime** [comment]
I will see how it all goes by using your implementation of viewmodels/worldmodels instead. I wish that it didn't turn the viewmodel into jolly ranchers due to lighting bugs, but if it doesn't break like the other one, I might as well use it. Thank you for your help, I'll let you know if any issues arise that cause the disappearing weapons bug again, if it still occurs on the live servers.
Please keep this issue opened until I can confirm this is indeed the case.

**Comment by nosoop** [comment]
Regarding viewmodels, you may want to look into [the `lighting-quirk-fix` branch](https://github.com/nosoop/SM-TFCWXBaseAttributes/tree/lighting-quirk-fix), but there's known issues with that one as well.

**Comment by SnowySnowtime** [comment]
It was indeed the one attachment causing all of these issues. Thank you for your assistance.
I've made a push request to the lighting-quirk-fix branch to attempt to update it, if you have time to review it.
