### ISSUE TITLE
Attributes on non-native wearables stack

### ISSUE THREAD

**Issue by nosoop** [nosoop/SM-TFCustomWeaponsX#30]
Separated out individual issue from #28, CC @SnowySnowtime

I'm almost certain this stems from wearables still being on the player.  `cwx/item_entity.sp::TF2_RemoveItemByLoadoutSlot()` only checks against the loadout entity, which means off-class loadouts aren't recognized or unequiped.

I thought I had an issue tracking this quirk somewhere in tf2utils.  There's a change there I've been meaning to push, so I'll test / deploy it if it works out.

**Comment by nosoop** [comment]
Ended up deciding not to do any changes to tf2utils for the time being.

**Comment by SnowySnowtime** [comment]
[tf_speakeasyinspired_weapons.txt](https://github.com/nosoop/SM-TFCustomWeaponsX/files/7005817/tf_speakeasyinspired_weapons.txt)

Example Config, for the issue mentioned above.

**Comment by nosoop** [comment]
Ah, that's an invalid combination &mdash; the item it's inheriting is strictly a wearable and not a wearable weapon like the Gunboats / Mantreads are.  That's something I'll have to error out on.

**Comment by nosoop** [comment]
Thanks for the config though; it provides an insight into the sort of creative ways that can break the plugin.

**Comment by nosoop** [comment]
Persistence improvements were made for off-class items, and a side effect of that appears to allow for wearables in non-native slots.  I tested your config again and it appears to work.

If you're still using the plugin, do try it and let me know!

**Comment by SnowySnowtime** [comment]
I'll try it out!

**Comment by SnowySnowtime** [comment]
It works, thank you!
