### ISSUE TITLE
Sound replacements not work

### ISSUE THREAD

**Issue by gaejuck** [nosoop/SM-TFCustomWeaponsX#37]
The [SM TF2 ReplaceSound](https://github.com/JessicaTheGunLady/SM-TF2-ReplaceSound) registered on the wiki is dependent on other plugins, so it does unnecessary behavior.  
and above all, it does not work properly. So I made another [one](https://github.com/gaejuck/SM-TF2-CA-ReplaceSound).
I want you register it on the wiki if there is no problem.

**Comment by nosoop** [comment]
Done &mdash; thanks for the contribution!
