### ISSUE TITLE
allow equipping of regular items?

### ISSUE THREAD

**Issue by Jailer0076** [nosoop/SM-TFCustomWeaponsX#39]
since a lot of the functions are already written here, could you allow the commands to also equip regular items so a separate plugin isnt needed? however i understand if you only want this plugin for custom items. thanks.

**Comment by nosoop** [comment]
It's indeed possible; there's nothing stopping server operators from creating configuration files that do nothing beyond inheriting existing items.

I'd rather leave that for other plugins / users to deal with, though.

**Comment by Jailer0076** [comment]
what i meant was modifying the equip commands to also accept regular item definitions as well as custom uuids, not adding each item into the config. but thats fine if you do not want to deal with it.
