### ISSUE TITLE
Weapon equip error spam + crash

### ISSUE THREAD

**Issue by Chizzor** [nosoop/SM-TFCustomWeaponsX#50]
Windows 10 64 Bit
Sourcemod version :  1.11.0.6922
CWX version :             X.0.10-cbf76ba

After the recent Vscript update, equipped custom weapons are permanently stuck to a player's right hand after switching weapons. This happens to all custom weapons regardless of stats used or attribute plugins accessed. Class and slot also don't seem to matter. Custom weapons still function as intended otherwise.

L 12/02/2022 - 18:07:34: [SM] Exception reported: Entity -1 (-1118764352) is not a valid entity
L 12/02/2022 - 18:07:34: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:34: [SM] Call stack trace:
L 12/02/2022 - 18:07:34: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:34: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:34: [SM] Exception reported: Entity -1 (-1383529666) is not a valid entity
L 12/02/2022 - 18:07:34: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:34: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-1312357564) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-637861048) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-1707932854) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-1313537204) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-956890260) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM]   [3] TF2_RegeneratePlayer
L 12/02/2022 - 18:07:35: [SM]   [4] Line 39, /home/forums/content/files/2/5/5/3/4/1/163360.attach::BackWeapons
L 12/02/2022 - 18:07:35: [SM] Exception reported: Entity -1 (-1503001744) is not a valid entity
L 12/02/2022 - 18:07:35: [SM] Blaming: cwx.smx
L 12/02/2022 - 18:07:35: [SM] Call stack trace:
L 12/02/2022 - 18:07:35: [SM]   [0] RemoveEntity
L 12/02/2022 - 18:07:35: [SM]   [1] Line 456, scripting/cwx.sp::OnGetLoadoutItemPost
L 12/02/2022 - 18:07:35: [SM]   [3] TF2_RegeneratePlayer
L 12/02/2022 - 18:07:35: [SM]   [4] Line 39, /home/forums/content/files/2/5/5/3/4/1/163360.attach::BackWeapons

This appears whenever someone touches a resupply while custom weapons are equipped, or when equipping a custom weapon. 

Crashes do occasionally happen but are inconsistent, and I could not pinpoint exactly what causes them, only that they happen with custom weapons in use when and seemingly after a player dies. No errors are thrown before or upon server crash

Replicating should be as simple as equipping a weapon, unless there are variables I haven't considered

[SM] Displaying 23 extensions:
[01] Automatic Updater (1.11.0.6922): Updates SourceMod gamedata files
[02] Webternet (1.11.0.6922): Extension for interacting with URLs
[03] TF2Items (1.6.4): TF2 Item Modifier
[04] TF2 CalculateMaxSpeed Detour (1.0.4): Allows overriding max speed results
[05] TF2 Tools (1.11.0.6922): TF2 extended functionality
[06] BinTools (1.11.0.6922): Low-level C/C++ Calling API
[07] SDK Hooks (1.11.0.6922): Source SDK Hooks
[08] SDK Tools (1.11.0.6922): Source SDK Tools
[09] Top Menus (1.11.0.6922): Creates sorted nested menus
[10] DHooks (1.11.0.6922): Dynamic Hooks
[11] Client Preferences (1.11.0.6922): Saves client preference settings
[12] SQLite (1.11.0.6922): SQLite Driver
[13] GeoIP (1.11.0.6922): Geographical IP information
[14] <OPTIONAL> file "geoipcity.ext.dll": The specified module could not be found.
 
[15] Regex (1.11.0.6922): Provides regex natives for plugins
[16] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[17] <OPTIONAL> file "store_sm.ext.dll": The specified module could not be found.
 
[18] SteamTools (0.10.0+54fdc51): SteamWorks for SourceMod
[19] Source Scramble (0.7.0): Tools for working with memory.
[20] <FAILED> file "PathFollower.ext.2.tf2.dll": Unknown error
[21] <OPTIONAL> file "curl.ext.dll": The specified module could not be found.
 
[22] Socket (3.0.1): Socket extension for SourceMod
[23] LoadSoundscript (1.1.0): More soundscript functionality for SourceMod plugins
[SM] Listing 145 plugins:
  001 "TF2 Add Condition" (1.0.0) by Tylerst
  002 "Admin File Reader" (1.11.0.6922) by AlliedModders LLC
  003 "Admin Smite" (2.1) by Hipster
  004 "Admin Help" (1.11.0.6922) by AlliedModders LLC
  005 "Admin Menu" (1.11.0.6922) by AlliedModders LLC
  006 "Admin Sounds" (1.0.1) by dalto
  007 "Admin Troll" (1.1.4a) by BB
  008 "Advertisements" (2.1.1) by Tsunami
  009 "airblast_projectiles_adds_self_condition.smx"
  010 "Anti-Flood" (1.11.0.6922) by AlliedModders LLC
  011 "[TF2CA] Medigun Uber: Group Overheal" (0.0.0) by Author!
  012 "attr_medic_disable_active_regen.smx"
  013 "[TF2CA] TF2 Classic Nailgun Slow" (1.0.0) by nosoop
  014 "Auto File Loader" (1.0.3) by Keith Warren (Shaders Allen)
  015 "Basic Ban Commands" (1.11.0.6922) by AlliedModders LLC
  016 "Basic Chat" (1.11.0.6922) by AlliedModders LLC
  017 "Basic Comm Control" (1.11.0.6922) by AlliedModders LLC
  018 "Basic Commands" (1.11.0.6922) by AlliedModders LLC
  019 "Basic Info Triggers" (1.11.0.6922) by AlliedModders LLC
  020 "Basic Votes" (1.11.0.6922) by AlliedModders LLC
  021 "Automatic Bot Names" (1.3.2) by Rakeri, luki1412
  022 "TFBot Rocket Jump" (1.0) by EfeDursun125
  023 "Bot Teamplay" (1.2.1) by Showin (Originally by Dr. McKay but I kinda completely changed it at this point.), Goerge
  024 "Class Restrictions for Bots" (3.01) by luki1412
  025 "TF2 Bot Combat Improvements" (1.6.5) by EfeDursun125, Marqueritte, Showin', and Crasher_3637
  026 "TF2 Improved Bots" (3.7) by EfeDursun125 / Tweaks And Comments By Showin
  027 "TF2 Bot Medic Fix" (1.0) by EfeDursun125
  028 "Bot Setup Time Fun" (1.0) by tRololo312312 / luki1412 / Showin
  029 "[TF2] Bot Voice Commands" (1.7.5) by EfeDursun125, enderandrew, Marqueritte, Showin', and Crasher_3637
  030 "[TF2] Building Hats" (2.0) by Pelipoika
  031 "Caberdemo Scream" (0.2) by hotgrits
  032 "CallAdmin" (0.1.8) by Impact, dordnung
  033 "Connect Announce" (1.8) by Arg!
  034 "[TF2] Custom Attribute : Replace Sound" (1.0) by Mir
  035 "[TF2] Chat Bubbles" (22w04a) by code: reBane, idea: fuffeh
  036 "[ANY] Chat Trigger to Lower Case" (1.0.0) by Mart
  037 "Civilian Pose Plugin" (1.0) by dada513
  038 "Client Preferences" (1.11.0.6922) by AlliedModders LLC
  039 "[TF2] Crit Hallelujah!" (1.0.1) by DarthNinja
  040 "Sounds Editor" (1.0) by Arkarr
  041 "[TF2] Serverside Player Attachment Fixer" (1.1) by 404UNF
  042 "Custom Votes" (1.9) by ReFlexPoison
  043 "Custom Weapons 2" (beta 2) by MasterOfTheXP
  044 "[TF2CA] Custom Weapons Config Adapter for Custom Attributes" (1.2.2) by nosoop
 
  045 "[TF2] Custom Weapons X - Custom Weapons 3 Attribute Adapter" (0.0.0) by nosoop
  046 "[TF2] Custom Weapons X" (X.0.10-cbf76ba) by nosoop
  047 "[TF2] Custom Weapons X - Equip Commands" (1.1.0) by nosoop
  048 "Class is dead voice systeam" (1.2) by Classic
  049 "Default Map Changer" (2.5) by TigerOx
  050 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
  051 "Discord: CallAdmin" (1.1) by .#Zipcore
  052 "Discord: SourceBans" (1.0) by .#Zipcore
  053 "Discord: SourceComms" (1.1) by .#Zipcore
  054 "disorient_on_hit.smx"
  055 "Custom Weapons: Dota 2 Attributes" (1.04) by Orion
  056 "[TF2] DSP Effects" (1.1) by A.I, Hurp Durp
  057 "Empty Server Map Restarter" (1.2) by Daniel Hambraeus
  058 "Frog Chance" (1.0) by MasterOfTheXP
  059 "Cheats" (1.1) by FaTony
  060 "Fun Commands" (1.11.0.6922) by AlliedModders LLC
  061 "Fun Votes" (1.11.0.6922) by AlliedModders LLC
  062 "[ANY] Gifts" (2.3) by Zephyrus
  063 "Give Bots More Weapons" (1.10) by PC Gamer, with code by luki1412 and manicogaming, edited by That Annoying Guide
  064 "Give Bots More Cosmetics" (1.13) by PC Gamer, with code by luki1412 and manicogaming
  065 "Goomba Stomp Core" (2.0.2) by Flyflo
  066 "Goomba Stomp TF2" (1.1.0) by Flyflo
  067 "invisfix.smx" (1.0) by kgbproject(Tetragromaton)
  068 "invisiwepfix" (1.0) by Frenzoid
  069 "joke_medigun_mod_drain_health.smx"
  070 "List SourceMod Commands" (1.1) by denormal, shanapu
  071 "MapChooser" (1.10.0.6543) by AlliedModders LLC
  072 "Map configs" (1.3) by Berni
  073 "minigun_radial_buff.smx"
  074 "mod_crit_type_on_hitgroup.smx"
  075 "mod_crit_type_vs_condition.smx"
  076 "Custom Weapons: More Advanced Weaponiser 2 Attributes" (1.04) by Orion && the AW2 dev team
  077 "MORE BOOM" (1.0) by psychonic
  078 "mult_basegrenade_explode_radius.smx"
  079 "[TF2] Necromasher" (1.1) by Pelipoika
  080 "Resize Players" (1.6.0) by 11530
  081 "Nextmap" (1.11.0.6922) by AlliedModders LLC
  082 "Noise Maker Player" (2.3.1) by Jouva Moufette <jouva@moufette.com>, DarthNinja, Velture
  083 "Map Nominations" (1.10.0.6543) by AlliedModders LLC
  084 "TF2 Utils" (1.2.1) by nosoop
  085 "Custom Weapons: Orion's Attributes" (1.04) by Orion
  086 "Panzer Tank Rockets" (0.2.1) by AI
  087 "Player Commands" (1.11.0.6922) by AlliedModders LLC
  088 "Player Pitch" (1.1.1) by mrphil2105
  089 "Player Ranks" (3.4.2) by Aderic, Gladoncio
  090 "pluginreloader.smx"
  091 "Profile Data Viewer" (0x01) by Chdata
  092 "Quake Sounds v3" (3.5.0) by Spartan_C001
  093 "It's Raining Men" (0.1) by Jindo
  094 "RandomCycle" (1.10.0.6543) by AlliedModders LLC
  095 "Reserved Slots" (1.11.0.6922) by AlliedModders LLC
  096 "[TF2] Respawn Effects" (3.2) by Lucas 'aIM' Maza
  097 "rocketdrop69.smx"
  098 "Rock The Vote" (1.10.0.6543) by AlliedModders LLC
  099 "Roll The Dice (Revamped)" (2.3.3) by Phil25
  100 "Round Triggers" (1.10) by MikeJS
  101 "Simple Chat Processor (Redux)" (2.3.0) by Simple Plugins, Mini
  102 "Simple Welcome Message" (1.2) by Zuko
  103 "SM File/Folder Downloader and Precacher" (1.5) by SWAT_88
  104 "sm_rsptc" (0.3) by gameguysz
  105 "Sound Commands" (1.11.0.6922) by AlliedModders LLC
  106 "[TF2] Special Ragdolls" (1.0) by Nanochip
  107 "stack_grenade_damage_custom.smx"
  108 "Steam Profile" (1.0.1) by Facksy
  109 "Store - The Resurrection" (1.0) by Zephyrus
  110 "[Any] SteamTools Game Description Override" (1.1.3) by Dr. McKay
  111 "[TF2] Stuck in spectate fix" (1.0) by Fraeven and Rowedahelicon
  112 "[TF2] TF2Attributes" (1.3.3@nosoop-1.7.1.1) by FlaminSarge
  113 "[TF2] TF2 Attribute Extended Support" (1.11.0) by nosoop
  114 "TF2 Hidden Attribuites" (1.2) by rafradek
  115 "[TF2] Hud Msg" (21w35a) by reBane
  116 "TF2IDB" (0.93) by Bottiger
  117 "[TF2Items] Give Weapon" (3.14159) by FlaminSarge (orig by asherkin)
  118 "[TF2Items] Manager" (1.4.3) by Damizean & Asherkin
  119 "Rebalanced Fortress 2" (v1.9.0) by JugadorXEI
  120 "[TF2] Wearable Item Tools" (1.1.1) by Powerlord
  121 "[TF2] Flags" (1.1) by Damizean
 
  122 "TF2 Fast Respawns" (1.0.8) by WoZeR, MonkeyBiz, gH0sTy, Downtown1, Kevin_b_er, SaberUK, octo-dhd
  123 "[TF2] Customizable Team Names" (1.0.3) by Oshizu�
  124 "TF Force Holidays" (1.10.2) by Powerlord
  125 "Engineer Bot Fix" (1.2) by EfeDursun125
  126 <Failed> "[TF2] TFBot engineer support for all maps" (1.3) by EfeDursun125
  127 "[TF2] Custom Attributes" (0.4.1) by nosoop
  128 "[TF2] Custom Attribute Debugger" (1.0.0) by nosoop
  129 "[TF2] Custom Attribute Manager" (1.0.0) by nosoop
  130 "[TF2] Custom Attribute Team Subsection Handler" (1.1.0) by nosoop
  131 "[TF2] DamageInfo Tools" (0.1.0) by nosoop
  132 "[TF2] Econ Data" (0.18.2) by nosoop
  133 "[TF2] OnTakeDamage Hooks" (1.2.0) by nosoop
  134 "[TF2] Spin the Wheel" (1.1) by FlaminSarge
  135 "[TF2] Taunt Menu" (1.08) by FlaminSarge, Nighty, xCoderx, Crow, PC Gamer
  136 "Tidy Chat" (0.5) by linux_lover
  137 "[Tf2] Third Person Cookies!" (1.3.5) by Friagram
  138 "[TF2] Unused Voicelines" (1.0) by Nanochip
  139 "Updater" (1.2.2) by GoD-Tony
  140 "Driveable Vehicles" (2.4.0) by Mikusch
  141 "viewmodel_override.smx"
  142 "VoiceCommand spam" (27.2.2021) by Bacardi
  143 "[TF2] Voice Commands Pitch" (1.1.1) by SirDigby
  144 "Web Shortcuts" (1.0.1) by James "sslice" Gray
  145 "[TF2]Wheel of Doom spawner" (1.3) by kgbproject(Tetragromaton)

**Comment by nosoop** [comment]
Thanks for the report; I believe the "not a valid entity" issue is resolved in the latest version of SourceMod (1.11.0.6923 or 1.12.0.6943); it looks like you're one release behind.

**Comment by Chizzor** [comment]
The newer, new version of sourcemod fixed the issue yes. Attention appreciated. Crashes are _probably_ due to other plugins. Attention appreciated

**Comment by nosoop** [comment]
Thanks for the confirmation; I've also checked and have not observed any crashes, so I'm going to go ahead and close this as completed.
