### ISSUE TITLE
Invalid Handle 0 (error 4)

### ISSUE THREAD

**Issue by lzardy** [nosoop/SM-TFCustomWeaponsX#58]
**Pre-flight checklist**

- [x] I am only describing a single issue.
- [x] I have upgraded to the latest version of CWX and its dependencies; the issue still persists.
- [x] I have verified that the issue is specific to CWX, and have ruled out other plugins that work indirectly with CWX (e.g. attributes).

**Environment**

- Operating system: Windows 10
- SourceMod version: 1.12.0.git1192-windows
- CWX version: X.0.10-2c22df4

**Description**

CWX attempts to load with a call to TF2Econ, resulting in the following error:
```
Exception reported: Invalid Handle 0 (error 4)
L 04/19/2024 - 03:56:19: [SM] Blaming: tf_econ_data.smx
L 04/19/2024 - 03:56:19: [SM] Call stack trace:
L 04/19/2024 - 03:56:19: [SM]   [0] SDKCall
L 04/19/2024 - 03:56:19: [SM]   [1] Line 495, scripting/tf_econ_data.sp::GetEconAttributeDefinitionByName
L 04/19/2024 - 03:56:19: [SM]   [2] Line 484, scripting/tf_econ_data.sp::Native_TranslateAttributeNameToDefinitionIndex
L 04/19/2024 - 03:56:19: [SM]   [4] TF2Econ_TranslateAttributeNameToDefinitionIndex
L 04/19/2024 - 03:56:19: [SM]   [5] Line 164, scripting/cwx.sp::OnAllPluginsLoaded
```

**Steps to replicate**

Install CWX and launch the server.

**Other information**

N/A

**Comment by nosoop** [comment]
Hi &mdash; this is not a CWX issue; the error directly mentions Econ Data.
Please download [the latest release of that](https://github.com/nosoop/SM-TFEconData/releases/tag/0.19.1.1) (the release was just posted so it's understandable if you thought it was unchanged); if the issue persists please open an issue in that repository.
