### ISSUE TITLE
Crash on Equip

### ISSUE THREAD

**Issue by lzardy** [nosoop/SM-TFCustomWeaponsX#59]
**Pre-flight checklist**

- [x] I am only describing a single issue.
- [x] I have upgraded to the latest version of CWX and its dependencies; the issue still persists.
- [ ] I have verified that the issue is specific to CWX, and have ruled out other plugins that work indirectly with CWX (e.g. attributes).

**Environment**

- Operating system: Windows 10
- SourceMod version: 1.12.0.git1192-windows
- CWX version: X.0.10-2c22df4

**Description**
Unfortunately no logs are printed as a result of this crash, however if necessary I can edit this post with a crash dump, let me know.

**Steps to replicate**

1. Install CWX (with pre-requisites)
2. Load into a map as pyro or demoman
3. Run `sm_cwx` command
4. Select a custom primary from the default example items
5. Expect immediate server crash

**Other information**

N/A

**Comment by nosoop** [comment]
It's likely that this crash was related to tf2attributes; [grab the latest release here](https://github.com/FlaminSarge/tf2attributes/releases/tag/v1.7.3.2).
