### ISSUE TITLE
Mod use metal ammo type seems to not work..

### ISSUE THREAD

**Issue by laurentmc0906** [nosoop/SM-TFCustomWeaponsX#65]
**Environment**

- Operating system:  Linux, unknown what version due to the fact that I'm using a host.
- SourceMod version:  SourceMod 1.11.0.6927, by AlliedModders LLC
- CWX version: X.0.10-c6f3e3e

**Description**

**Steps to replicate**
It's pretty self explanatory, but here is my weapon file:
![image](https://github.com/user-attachments/assets/a7b26647-cfed-4cf2-a573-8adaf1d6d6fa)

**Comment by nosoop** [comment]
Even if it is self-explanatory, having a weapon config on hand saves me time in having to write one to repro the issue and provide a fix.

Thanks for the report; should be fixed in a release coming shortly.

**Comment by nosoop** [comment]
Note that you will also need to set `mod_max_primary_clip_override` to -1 to disable the clip; otherwise it will have a normal-sized clip that won't drain metal until reloading.
